import operator		#This will imported operator library.

operation =	{
    			'+': operator.add,	#This will define '+' string as addition operator.
    			'-': operator.sub,	#This will define '-' string as addition operator.
   				'*': operator.mul,	#This will define '*' string as addition operator.
			}

numberr = int(input("Enter a number except 0 : "))	#The input from user is a string here we converted that string to integer. 

desired_operator = input("Choose a math operation (+), (-) or (*) : ")	#Intracting with user and taking input.

for i in range(1, 10):	#This is a for loop.
    output = operation[desired_operator](float(numberr), i)	#Stored the result in variable after using the operator on input number and number i generated by loop. 
    print(output)	#This will print the output.